service: miranda-backend
frameworkVersion: "3"
package:
  patterns:
    - "!./**"
    - "package.json"
    - "node_modules/**"
    - "dist/**"
provider:
  name: aws
  region: eu-west-3
  environment:
    MYSQL_HOST: ${file(.env.json):MYSQL_HOST}
    MYSQL_USER: ${file(.env.json):MYSQL_USER}
    MYSQL_PASS: ${file(.env.json):MYSQL_PASS}
    MYSQL_DB: ${file(.env.json):MYSQL_DB}
    SECRET: ${file(.env.json):SECRET}
    MONGO_URL: ${file(.env.json):MONGO_URL}
  runtime: nodejs18.x
functions:
  app:
    handler: dist/lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
