name: Despliegue Api Dashboard

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js v20.9.0
      uses: actions/setup-node@v4
      with:
          node-version: v20.9.0
    - name: Install Dependencies
      run: npm install
    - name: Build Project
      run: npm run build
    - name: serverless deploy
      uses: serverless/github-action@v3.2
      with:
        args: deploy
      env:
          # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          # or if using AWS credentials directly
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
